### ISSUE TITLE
电脑版元素被遮挡

### ISSUE THREAD

**Issue by cyclinbox** [Liu-HJ/Project-Raki#2]
![图片](https://user-images.githubusercontent.com/57782663/90021811-54b4a300-dce4-11ea-86b8-dbc461c9636f.png)
如图所示，Project Raki这几个字母的下半部分被遮挡。使用环境：win10家庭版2004（64位），firefox中国版79.0（64位）。

**Comment by Liu-HJ** [comment]
chrome与safari暂未出现问题，稍后我是用firefox测试，感谢

**Comment by Liu-HJ** [comment]
已确认firefox出现该问题，原因是min-height元素设置为60vh，而非100vh，已修改。
并将移动端和电脑端css分别处理
